// Generated by gencpp from file launchtest/FirstRequest.msg
// DO NOT EDIT!


#ifndef LAUNCHTEST_MESSAGE_FIRSTREQUEST_H
#define LAUNCHTEST_MESSAGE_FIRSTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace launchtest
{
template <class ContainerAllocator>
struct FirstRequest_
{
  typedef FirstRequest_<ContainerAllocator> Type;

  FirstRequest_()
    : val(0)  {
    }
  FirstRequest_(const ContainerAllocator& _alloc)
    : val(0)  {
  (void)_alloc;
    }



   typedef int32_t _val_type;
  _val_type val;





  typedef boost::shared_ptr< ::launchtest::FirstRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::launchtest::FirstRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FirstRequest_

typedef ::launchtest::FirstRequest_<std::allocator<void> > FirstRequest;

typedef boost::shared_ptr< ::launchtest::FirstRequest > FirstRequestPtr;
typedef boost::shared_ptr< ::launchtest::FirstRequest const> FirstRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::launchtest::FirstRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::launchtest::FirstRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::launchtest::FirstRequest_<ContainerAllocator1> & lhs, const ::launchtest::FirstRequest_<ContainerAllocator2> & rhs)
{
  return lhs.val == rhs.val;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::launchtest::FirstRequest_<ContainerAllocator1> & lhs, const ::launchtest::FirstRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace launchtest

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::launchtest::FirstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::launchtest::FirstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::launchtest::FirstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::launchtest::FirstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::launchtest::FirstRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::launchtest::FirstRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::launchtest::FirstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50ce5d329885e7178604b54270ec733c";
  }

  static const char* value(const ::launchtest::FirstRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50ce5d329885e717ULL;
  static const uint64_t static_value2 = 0x8604b54270ec733cULL;
};

template<class ContainerAllocator>
struct DataType< ::launchtest::FirstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "launchtest/FirstRequest";
  }

  static const char* value(const ::launchtest::FirstRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::launchtest::FirstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 val\n"
;
  }

  static const char* value(const ::launchtest::FirstRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::launchtest::FirstRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FirstRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::launchtest::FirstRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::launchtest::FirstRequest_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAUNCHTEST_MESSAGE_FIRSTREQUEST_H
