// Generated by gencpp from file pow_service/first.msg
// DO NOT EDIT!


#ifndef POW_SERVICE_MESSAGE_FIRST_H
#define POW_SERVICE_MESSAGE_FIRST_H

#include <ros/service_traits.h>


#include <pow_service/firstRequest.h>
#include <pow_service/firstResponse.h>


namespace pow_service
{

struct first
{

typedef firstRequest Request;
typedef firstResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct first
} // namespace pow_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pow_service::first > {
  static const char* value()
  {
    return "12cec05e53e1a1cd50861b841b371c18";
  }

  static const char* value(const ::pow_service::first&) { return value(); }
};

template<>
struct DataType< ::pow_service::first > {
  static const char* value()
  {
    return "pow_service/first";
  }

  static const char* value(const ::pow_service::first&) { return value(); }
};


// service_traits::MD5Sum< ::pow_service::firstRequest> should match
// service_traits::MD5Sum< ::pow_service::first >
template<>
struct MD5Sum< ::pow_service::firstRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pow_service::first >::value();
  }
  static const char* value(const ::pow_service::firstRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pow_service::firstRequest> should match
// service_traits::DataType< ::pow_service::first >
template<>
struct DataType< ::pow_service::firstRequest>
{
  static const char* value()
  {
    return DataType< ::pow_service::first >::value();
  }
  static const char* value(const ::pow_service::firstRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pow_service::firstResponse> should match
// service_traits::MD5Sum< ::pow_service::first >
template<>
struct MD5Sum< ::pow_service::firstResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pow_service::first >::value();
  }
  static const char* value(const ::pow_service::firstResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pow_service::firstResponse> should match
// service_traits::DataType< ::pow_service::first >
template<>
struct DataType< ::pow_service::firstResponse>
{
  static const char* value()
  {
    return DataType< ::pow_service::first >::value();
  }
  static const char* value(const ::pow_service::firstResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POW_SERVICE_MESSAGE_FIRST_H
