// Generated by gencpp from file msg_test/firstRequest.msg
// DO NOT EDIT!


#ifndef MSG_TEST_MESSAGE_FIRSTREQUEST_H
#define MSG_TEST_MESSAGE_FIRSTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_test
{
template <class ContainerAllocator>
struct firstRequest_
{
  typedef firstRequest_<ContainerAllocator> Type;

  firstRequest_()
    : val(0)  {
    }
  firstRequest_(const ContainerAllocator& _alloc)
    : val(0)  {
  (void)_alloc;
    }



   typedef int32_t _val_type;
  _val_type val;





  typedef boost::shared_ptr< ::msg_test::firstRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_test::firstRequest_<ContainerAllocator> const> ConstPtr;

}; // struct firstRequest_

typedef ::msg_test::firstRequest_<std::allocator<void> > firstRequest;

typedef boost::shared_ptr< ::msg_test::firstRequest > firstRequestPtr;
typedef boost::shared_ptr< ::msg_test::firstRequest const> firstRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_test::firstRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_test::firstRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_test::firstRequest_<ContainerAllocator1> & lhs, const ::msg_test::firstRequest_<ContainerAllocator2> & rhs)
{
  return lhs.val == rhs.val;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_test::firstRequest_<ContainerAllocator1> & lhs, const ::msg_test::firstRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msg_test::firstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_test::firstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_test::firstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_test::firstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_test::firstRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_test::firstRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_test::firstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50ce5d329885e7178604b54270ec733c";
  }

  static const char* value(const ::msg_test::firstRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50ce5d329885e717ULL;
  static const uint64_t static_value2 = 0x8604b54270ec733cULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_test::firstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_test/firstRequest";
  }

  static const char* value(const ::msg_test::firstRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_test::firstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 val\n"
;
  }

  static const char* value(const ::msg_test::firstRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_test::firstRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct firstRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_test::firstRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_test::firstRequest_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_TEST_MESSAGE_FIRSTREQUEST_H
